###
POST http://localhost:8080/Bingo-API/players
Content-Type: application/json

{
  "name": "matheus",
  "email": "SD@gmail.com"
}

###
GET http://localhost:8080/Bingo-API/players
Content-Type: application/json

###
PUT http://localhost:8080/Bingo-API/players/679555423355ff288614c847
Content-Type: application/json
Accept: application/json

{
  "name": "Jamal",
  "email": "jamal@gmail.com"
}

###
DELETE http://localhost:8080/Bingo-API/players/67955529c355ff288614c846

###
POST http://localhost:8080/Bingo-API/rounds
Content-Type: application/json

###
POST http://localhost:8080/Bingo-API/rounds/6796d27ea7abd03c01c2b1d5/generate-number
Content-Type: application/json

###
POST http://localhost:8080/Bingo-API/rounds/6796d355a7abd03c01c2b1d6/bingo-card/6796d270a7abd03c01c2b1d4
Content-Type: application/json

###
GET http://localhost:8080/Bingo-API/rounds/6796d355a7abd03c01c2b1d6