spring.application.name=Bingo-API

spring.webflux.base-path=/Bingo-API
spring.data.mongodb.uri=mongodb://mongo-admin:neymar@localhost:27017/Bingo?authSource=admin

spring.mail.host=mailcatcher
spring.mail.properties.mail.transport.protocol=smtp
spring.mail.properties.mail.smtp.port=1025

bingo-api.mail.sender=Bingo Api <noreply@bingoapi.com.br>

retry-config.max-retries=3
retry-config.min-duration=1
